In [16]:
import numpy as np
import pandas as pd

from collections import defaultdict, deque

pd.set_option('display.max_columns', None)

In [17]:
df = pd.read_csv("../data/raw/1993-94.csv")
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,E0,14/08/93,Arsenal,Coventry,0.0,3.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/93,Aston Villa,QPR,4.0,1.0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/93,Chelsea,Blackburn,1.0,2.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/93,Liverpool,Sheffield Weds,2.0,0.0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/93,Man City,Leeds,1.0,1.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.shape

(552, 28)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Div          462 non-null    str
 1   Date         462 non-null    str
 2   HomeTeam     462 non-null    str
 3   AwayTeam     462 non-null    str
 4   FTHG         462 non-null    float64
 5   FTAG         462 non-null    float64
 6   FTR          462 non-null    str
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  0 non-null      float64
 15  Unnamed: 15  0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  Unnamed: 23  0 non-null      float64
 24  Unnamed: 24  0 non-null      float64
 25  Unnamed: 25  0 non-null      float64
 26  Unnamed: 26  0 non-null      float64
 27  Unnamed: 27  0 non-null      float64
dtypes: float64(23), str(5)
memory usage: 120.9 KB

In [20]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       462 non-null    str
 1   Date      462 non-null    str
 2   HomeTeam  462 non-null    str
 3   AwayTeam  462 non-null    str
 4   FTHG      462 non-null    float64
 5   FTAG      462 non-null    float64
 6   FTR       462 non-null    str
dtypes: float64(2), str(5)
memory usage: 30.3 KB

In [21]:
df = df.drop_duplicates()

In [22]:
df = df.dropna(how='all')

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       462 non-null    str
 1   Date      462 non-null    str
 2   HomeTeam  462 non-null    str
 3   AwayTeam  462 non-null    str
 4   FTHG      462 non-null    float64
 5   FTAG      462 non-null    float64
 6   FTR       462 non-null    str
dtypes: float64(2), str(5)
memory usage: 25.4 KB

In [24]:
df.tail()

    Div      Date        HomeTeam     AwayTeam  FTHG  FTAG FTR
457  E0  07/05/94  Sheffield Weds     Man City   1.0   1.0   D
458  E0  07/05/94         Swindon        Leeds   0.0   5.0   A
459  E0  07/05/94       Tottenham          QPR   1.0   2.0   A
460  E0  07/05/94        West Ham  Southampton   3.0   3.0   D
461  E0  08/05/94      Man United     Coventry   0.0   0.0   D

In [25]:
# Convertir fecha y ordenar
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date").reset_index(drop=True)
df.head()

C:\Users\sergi\AppData\Local\Temp\ipykernel_500\3278115852.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

  Div       Date        HomeTeam          AwayTeam  FTHG  FTAG FTR
0  E0 1993-01-09       Tottenham           Chelsea   1.0   1.0   D
1  E0 1993-01-09         Swindon          Man City   1.0   3.0   A
2  E0 1993-01-09  Sheffield Weds           Norwich   3.0   3.0   D
3  E0 1993-01-09             QPR  Sheffield United   2.0   1.0   H
4  E0 1993-01-09      Man United          West Ham   3.0   0.0   H

In [26]:
# Historial general
hist_results = defaultdict(lambda: deque(maxlen=5))
hist_goals_for = defaultdict(lambda: deque(maxlen=5))
hist_goals_against = defaultdict(lambda: deque(maxlen=5))

# Local / visitante
hist_home = defaultdict(lambda: deque(maxlen=5))
hist_away = defaultdict(lambda: deque(maxlen=5))

# Head to head
h2h = defaultdict(lambda: deque(maxlen=3))

# Temporada
season_gf = defaultdict(int)
season_ga = defaultdict(int)

# ELO
elo = defaultdict(lambda: 1500)

# Última fecha (para descanso)
last_match_date = {}

In [27]:
def result_to_points(r):
    return 3 if r == "W" else 1 if r == "D" else 0


def weighted_points(results):
    weights = [1, 2, 3, 4, 5]  # más peso al más reciente
    return sum(result_to_points(r) * w for r, w in zip(results, weights[-len(results):]))


def elo_expected(rating_a, rating_b):
    return 1 / (1 + 10 ** ((rating_b - rating_a) / 400))


def update_elo(r_a, r_b, score_a, k=20):
    exp_a = elo_expected(r_a, r_b)
    return r_a + k * (score_a - exp_a)

In [28]:
features = []

for _, row in df.iterrows():

    home = row["HomeTeam"]
    away = row["AwayTeam"]
    hg = row["FTHG"]
    ag = row["FTAG"]
    date = row["Date"]

    # Resultado
    if hg > ag:
        hr, ar = "W", "L"
        score_home = 1
    elif hg < ag:
        hr, ar = "L", "W"
        score_home = 0
    else:
        hr, ar = "D", "D"
        score_home = 0.5

    # =========================
    # FEATURES (ANTES)
    # =========================

    # Forma reciente
    home_points_5 = sum(result_to_points(r) for r in hist_results[home])
    away_points_5 = sum(result_to_points(r) for r in hist_results[away])

    # Forma ponderada
    home_weighted = weighted_points(hist_results[home])
    away_weighted = weighted_points(hist_results[away])

    # Goles
    home_gf_5 = sum(hist_goals_for[home])
    home_ga_5 = sum(hist_goals_against[home])

    away_gf_5 = sum(hist_goals_for[away])
    away_ga_5 = sum(hist_goals_against[away])

    # Dif goles
    home_diff_5 = home_gf_5 - home_ga_5
    away_diff_5 = away_gf_5 - away_ga_5

    # Local / visitante
    home_home_points = sum(result_to_points(r) for r in hist_home[home])
    away_away_points = sum(result_to_points(r) for r in hist_away[away])

    # Head to head
    pair = tuple(sorted([home, away]))
    h2h_points = sum(result_to_points(r) for r in h2h[pair])

    # ELO
    elo_home = elo[home]
    elo_away = elo[away]

    # Descanso
    rest_home = (date - last_match_date.get(home, date)).days
    rest_away = (date - last_match_date.get(away, date)).days

    # Guardar features
    features.append({
        "home_points_5": home_points_5,
        "away_points_5": away_points_5,
        "home_weighted": home_weighted,
        "away_weighted": away_weighted,
        "home_diff_5": home_diff_5,
        "away_diff_5": away_diff_5,
        "home_home_points": home_home_points,
        "away_away_points": away_away_points,
        "h2h_points": h2h_points,
        "elo_home": elo_home,
        "elo_away": elo_away,
        "rest_home": rest_home,
        "rest_away": rest_away,
    })

    # =========================
    # UPDATE (DESPUÉS)
    # =========================

    # Historial
    hist_results[home].append(hr)
    hist_results[away].append(ar)

    hist_goals_for[home].append(hg)
    hist_goals_for[away].append(ag)

    hist_goals_against[home].append(ag)
    hist_goals_against[away].append(hg)

    # Local / visitante
    hist_home[home].append(hr)
    hist_away[away].append(ar)

    # Head to head
    h2h[pair].append(hr)

    # Temporada
    season_gf[home] += hg
    season_ga[home] += ag
    season_gf[away] += ag
    season_ga[away] += hg

    # ELO update
    elo[home] = update_elo(elo[home], elo[away], score_home)
    elo[away] = update_elo(elo[away], elo[home], 1 - score_home)

    # Última fecha
    last_match_date[home] = date
    last_match_date[away] = date

In [29]:
df_features = pd.DataFrame(features)
df = pd.concat([df, df_features], axis=1)

In [30]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,home_points_5,away_points_5,home_weighted,away_weighted,home_diff_5,away_diff_5,home_home_points,away_away_points,h2h_points,elo_home,elo_away,rest_home,rest_away
0,E0,1993-01-09,Tottenham,Chelsea,1.0,1.0,D,0,0,0,0,0.0,0.0,0,0,0,1500.000000,1500.000000,0,0
1,E0,1993-01-09,Swindon,Man City,1.0,3.0,A,0,0,0,0,0.0,0.0,0,0,0,1500.000000,1500.000000,0,0
2,E0,1993-01-09,Sheffield Weds,Norwich,3.0,3.0,D,0,0,0,0,0.0,0.0,0,0,0,1500.000000,1500.000000,0,0
3,E0,1993-01-09,QPR,Sheffield United,2.0,1.0,H,0,0,0,0,0.0,0.0,0,0,0,1500.000000,1500.000000,0,0
4,E0,1993-01-09,Man United,West Ham,3.0,0.0,H,0,0,0,0,0.0,0.0,0,0,0,1500.000000,1500.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,E0,1994-12-03,Man City,Wimbledon,0.0,1.0,A,9,9,25,27,2.0,1.0,9,4,3,1488.333187,1542.617766,1,1
458,E0,1994-12-03,Aston Villa,Ipswich,0.0,1.0,A,12,2,33,8,7.0,-6.0,10,2,0,1499.379053,1431.596326,1,1
459,E0,1994-12-03,Southampton,Sheffield Weds,1.0,1.0,D,8,8,25,26,3.0,3.0,6,8,3,1451.198176,1545.340194,90,90
460,E0,1994-12-03,Norwich,QPR,3.0,4.0,A,5,4,9,15,-2.0,-4.0,2,8,1,1472.959633,1498.718317,90,90
461,E0,1994-12-03,Newcastle,Swindon,7.0,1.0,H,6,7,15,12,-2.0,-6.0,13,4,1,1569.224498,1420.182739,1,1