In [117]:
import numpy as np
import pandas as pd

from collections import deque

In [118]:
df = pd.read_csv("../data/raw/1993-94.csv")
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,E0,14/08/93,Arsenal,Coventry,0.0,3.0,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/93,Aston Villa,QPR,4.0,1.0,H,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/93,Chelsea,Blackburn,1.0,2.0,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/93,Liverpool,Sheffield Weds,2.0,0.0,H,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/93,Man City,Leeds,1.0,1.0,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
df.shape

(552, 28)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Div          462 non-null    str
 1   Date         462 non-null    str
 2   HomeTeam     462 non-null    str
 3   AwayTeam     462 non-null    str
 4   FTHG         462 non-null    float64
 5   FTAG         462 non-null    float64
 6   FTR          462 non-null    str
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  0 non-null      float64
 15  Unnamed: 15  0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  Unnamed: 23  0 non-null      float64
 24  Unnamed: 24  0 non-null      float64
 25  Unnamed: 25  0 non-null      float64
 26  Unnamed: 26  0 non-null      float64
 27  Unnamed: 27  0 non-null      float64
dtypes: float64(23), str(5)
memory usage: 120.9 KB

In [121]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       462 non-null    str
 1   Date      462 non-null    str
 2   HomeTeam  462 non-null    str
 3   AwayTeam  462 non-null    str
 4   FTHG      462 non-null    float64
 5   FTAG      462 non-null    float64
 6   FTR       462 non-null    str
dtypes: float64(2), str(5)
memory usage: 30.3 KB

In [122]:
df = df.drop_duplicates()

In [123]:
df = df.dropna(how='all')

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       462 non-null    str
 1   Date      462 non-null    str
 2   HomeTeam  462 non-null    str
 3   AwayTeam  462 non-null    str
 4   FTHG      462 non-null    float64
 5   FTAG      462 non-null    float64
 6   FTR       462 non-null    str
dtypes: float64(2), str(5)
memory usage: 25.4 KB

In [125]:
df.tail()

    Div      Date        HomeTeam     AwayTeam  FTHG  FTAG FTR
457  E0  07/05/94  Sheffield Weds     Man City   1.0   1.0   D
458  E0  07/05/94         Swindon        Leeds   0.0   5.0   A
459  E0  07/05/94       Tottenham          QPR   1.0   2.0   A
460  E0  07/05/94        West Ham  Southampton   3.0   3.0   D
461  E0  08/05/94      Man United     Coventry   0.0   0.0   D

In [126]:
# # Diccionario para guardar historial de cada equipo
# historial = {}

# # Listas para almacenar resultados
# rachas_home = []
# rachas_away = []

# for idx, row in df.iterrows():
#     home = row['HomeTeam']
#     away = row['AwayTeam']
    
#     # Racha de los últimos 5 (excluyendo partido actual) - como LISTA
#     racha_home = historial.get(home, [])[-5:] if home in historial else []
#     racha_away = historial.get(away, [])[-5:] if away in historial else []
    
#     rachas_home.append(racha_home if racha_home else [])  # Lista vacía si no hay historial
#     rachas_away.append(racha_away if racha_away else [])
    
#     # Actualizar historial con resultado de ESTE partido
#     if row['FTR'] == 'H':
#         historial.setdefault(home, []).append('G')
#         historial.setdefault(away, []).append('P')
#     elif row['FTR'] == 'A':
#         historial.setdefault(home, []).append('P')
#         historial.setdefault(away, []).append('G')
#     else:  # 'D'
#         historial.setdefault(home, []).append('E')
#         historial.setdefault(away, []).append('E')

# # Añadir al DataFrame
# df['racha_home'] = rachas_home
# df['racha_away'] = rachas_away

In [ ]:
# Diccionarios para guardar historial

historial_general = {}      # Guardará TODOS los partidos de cada equipo (local y visitante)
historial_local = {}        # Guardará SOLO los partidos que cada equipo juega como LOCAL
historial_visitante = {}    # Guardará SOLO los partidos que cada equipo juega como VISITANTE

# Listas para almacenar resultados
# Cada lista tendrá un elemento por cada fila/partido del DataFrame
rachas_general_home = []    # Racha GENERAL del equipo LOCAL en cada partido
rachas_general_away = []    # Racha GENERAL del equipo VISITANTE en cada partido
rachas_local_home = []      # Racha como LOCAL del equipo LOCAL en cada partido
rachas_visitante_away = []  # Racha como VISITANTE del equipo VISITANTE en cada partido

# Bucle principal: iteramos fila por fila del DataFrame
# df.iterrows() devuelve (índice, fila) para cada partido
for idx, row in df.iterrows():
    
    # Extraemos los nombres de los equipos de la fila actual
    home = row['HomeTeam']  # Equipo que juega en casa (local)
    away = row['AwayTeam']  # Equipo que juega fuera (visitante)
    
    # ========== 1. CALCULAR RACHAS (sin incluir el partido actual) ==========
    
    # Racha GENERAL del equipo LOCAL:
    # - historial_general.get(home, []) : Busca la lista de resultados del equipo 'home'
    #   Si no existe (primer partido), devuelve una lista vacía []
    # - [-5:] : Toma los últimos 5 elementos de la lista (slicing de Python)
    # - if home in historial_general else [] : Si el equipo no tiene historial, lista vacía
    racha_general_home_actual = historial_general.get(home, [])[-5:] if home in historial_general else []
    
    # Racha GENERAL del equipo VISITANTE (misma lógica pero para el visitante)
    racha_general_away_actual = historial_general.get(away, [])[-5:] if away in historial_general else []
    
    # Racha como LOCAL del equipo LOCAL:
    # Buscamos en historial_local (solo partidos en casa) los últimos 5 del equipo local
    racha_local_home_actual = historial_local.get(home, [])[-5:] if home in historial_local else []
    
    # Racha como VISITANTE del equipo VISITANTE:
    # Buscamos en historial_visitante (solo partidos fuera) los últimos 5 del equipo visitante
    racha_visitante_away_actual = historial_visitante.get(away, [])[-5:] if away in historial_visitante else []
    
    # ========== 2. GUARDAR LAS RACHAS EN LAS LISTAS ==========
    # Añadimos cada racha calculada a su lista correspondiente
    # Estas listas mantienen el orden de los partidos (fila 0, fila 1, fila 2...)
    rachas_general_home.append(racha_general_home_actual)
    rachas_general_away.append(racha_general_away_actual)
    rachas_local_home.append(racha_local_home_actual)
    rachas_visitante_away.append(racha_visitante_away_actual)
    
    # ========== 3. DETERMINAR EL RESULTADO PARA CADA EQUIPO ==========
    # FTR (Full Time Result) puede ser:
    # 'H' = Home win (gana el local)
    # 'A' = Away win (gana el visitante)
    # 'D' = Draw (empate)
    
    if row['FTR'] == 'H':  # Si gana el equipo LOCAL
        res_local = 'G'    # 'G' = Ganó (para el local)
        res_visitante = 'P' # 'P' = Perdió (para el visitante)
    elif row['FTR'] == 'A':  # Si gana el equipo VISITANTE
        res_local = 'P'     # 'P' = Perdió (para el local)
        res_visitante = 'G' # 'G' = Ganó (para el visitante)
    else:  # row['FTR'] == 'D' - Empate
        res_local = 'E'     # 'E' = Empate (para el local)
        res_visitante = 'E' # 'E' = Empate (para el visitante)
    
    # ========== 4. ACTUALIZAR HISTORIALES (para partidos FUTUROS) ==========
    
    # ACTUALIZAR HISTORIAL GENERAL (ambos equipos)
    # setdefault(key, []) funciona así:
    # - Si la clave 'home' existe, devuelve su lista
    # - Si NO existe, crea la clave con una lista vacía [] y la devuelve
    # Luego .append() añade el resultado al final de la lista
    historial_general.setdefault(home, []).append(res_local)    # Añade resultado del local
    historial_general.setdefault(away, []).append(res_visitante) # Añade resultado del visitante
    
    # ACTUALIZAR HISTORIAL COMO LOCAL (solo el equipo LOCAL)
    # Solo el equipo que juega en casa actualiza su racha de local
    # Esto es importante: un equipo NO actualiza su racha de local cuando juega fuera
    historial_local.setdefault(home, []).append(res_local)
    
    # ACTUALIZAR HISTORIAL COMO VISITANTE (solo el equipo VISITANTE)
    # Solo el equipo que juega fuera actualiza su racha de visitante
    # Un equipo NO actualiza su racha de visitante cuando juega en casa
    historial_visitante.setdefault(away, []).append(res_visitante)

# ========== 5. AÑADIR LAS COLUMNAS AL DATAFRAME ORIGINAL ==========
# Una vez procesados todos los partidos, añadimos las listas como nuevas columnas
df['racha_general_home'] = rachas_general_home    # Columna con racha general del local
df['racha_general_away'] = rachas_general_away    # Columna con racha general del visitante
df['racha_local_home'] = rachas_local_home        # Columna con racha como local del local
df['racha_visitante_away'] = rachas_visitante_away # Columna con racha como visitante del visitante

In [128]:
df[(df["HomeTeam"] == "Arsenal") | (df["AwayTeam"] == "Arsenal")]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,racha_general_home,racha_general_away,racha_local_home,racha_visitante_away
0,E0,14/08/93,Arsenal,Coventry,0.0,3.0,A,[],[],[],[]
11,E0,16/08/93,Tottenham,Arsenal,0.0,1.0,A,[G],[P],[],[]
29,E0,21/08/93,Sheffield Weds,Arsenal,0.0,1.0,A,"[P, E]","[P, G]",[E],[G]
34,E0,24/08/93,Arsenal,Leeds,2.0,1.0,H,"[P, G, G]","[E, G, P]",[P],[E]
45,E0,28/08/93,Arsenal,Everton,2.0,0.0,H,"[P, G, G, G]","[G, G, G, P]","[P, G]","[G, P]"
59,E0,01/09/93,Blackburn,Arsenal,1.0,1.0,D,"[G, P, G, G, E]","[P, G, G, G, G]","[P, G]","[G, G]"
66,E0,11/09/93,Arsenal,Ipswich,4.0,0.0,H,"[G, G, G, G, E]","[G, G, P, E, E]","[P, G, G]","[G, P, E]"
86,E0,19/09/93,Man United,Arsenal,1.0,0.0,H,"[E, G, G, G, P]","[G, G, G, E, G]","[G, E, G]","[G, G, E]"
88,E0,25/09/93,Arsenal,Southampton,1.0,0.0,H,"[G, G, E, G, P]","[G, P, P, P, P]","[P, G, G, G]","[P, P, P, P]"
101,E0,02/10/93,Liverpool,Arsenal,0.0,0.0,D,"[G, P, P, P, P]","[G, E, G, P, G]","[G, P, G, P]","[G, G, E, P]"
110,E0,16/10/93,Arsenal,Man City,0.0,0.0,D,"[E, G, P, G, E]","[G, G, P, G, E]","[P, G, G, G, G]","[P, P, G, P, G]"
126,E0,23/10/93,Oldham,Arsenal,0.0,0.0,D,"[P, P, E, E, P]","[G, P, G, E, E]","[P, E, E, P, E]","[G, G, E, P, E]"
132,E0,30/10/93,Arsenal,Norwich,0.0,0.0,D,"[P, G, E, E, E]","[E, G, G, G, E]","[G, G, G, G, E]","[G, E, E, G, G]"
143,E0,06/11/93,Arsenal,Aston Villa,1.0,2.0,A,"[G, E, E, E, E]","[E, P, E, G, G]","[G, G, G, E, E]","[G, G, E, E, G]"
156,E0,20/11/93,Chelsea,Arsenal,0.0,2.0,A,"[P, P, P, P, P]","[E, E, E, E, P]","[E, G, G, P, P]","[G, E, P, E, E]"
174,E0,24/11/93,West Ham,Arsenal,0.0,0.0,D,"[E, E, G, P, G]","[E, E, E, P, G]","[E, G, E, G, G]","[E, P, E, E, G]"
175,E0,27/11/93,Arsenal,Newcastle,2.0,1.0,H,"[E, E, P, G, E]","[P, G, G, G, G]","[G, G, E, E, P]","[E, E, G, P, G]"
186,E0,04/12/93,Coventry,Arsenal,1.0,0.0,H,"[E, G, E, P, P]","[E, P, G, E, G]","[P, E, E, G, P]","[P, E, E, G, E]"
197,E0,06/12/93,Arsenal,Tottenham,1.0,1.0,D,"[P, G, E, G, P]","[P, E, E, E, P]","[G, E, E, P, G]","[E, P, P, P, E]"
214,E0,12/12/93,Arsenal,Sheffield Weds,1.0,0.0,H,"[G, E, G, P, E]","[E, G, G, G, E]","[E, E, P, G, E]","[E, E, G, G, E]"
220,E0,18/12/93,Leeds,Arsenal,2.0,1.0,H,"[E, G, G, G, P]","[E, G, P, E, G]","[G, E, G, G, G]","[E, E, G, E, P]"
234,E0,27/12/93,Swindon,Arsenal,0.0,4.0,A,"[P, E, P, E, G]","[G, P, E, G, P]","[P, E, G, E, G]","[E, G, E, P, P]"
240,E0,29/12/93,Arsenal,Sheffield United,3.0,0.0,H,"[P, E, G, P, G]","[E, P, E, P, E]","[E, P, G, E, G]","[E, P, P, E, P]"
256,E0,01/01/94,Wimbledon,Arsenal,0.0,3.0,A,"[P, G, G, P, E]","[E, G, P, G, G]","[G, E, P, G, P]","[G, E, P, P, G]"
257,E0,03/01/94,Arsenal,QPR,0.0,0.0,D,"[G, P, G, G, G]","[P, G, G, E, P]","[P, G, E, G, G]","[G, P, P, G, E]"
267,E0,15/01/94,Man City,Arsenal,0.0,0.0,D,"[G, P, P, E, P]","[P, G, G, G, E]","[P, P, G, P, E]","[E, P, P, G, G]"
275,E0,22/01/94,Arsenal,Oldham,1.0,1.0,D,"[G, G, G, E, E]","[E, P, P, P, P]","[G, E, G, G, E]","[P, E, E, P, P]"
303,E0,13/02/94,Norwich,Arsenal,1.0,1.0,D,"[G, P, E, E, E]","[G, G, E, E, E]","[G, P, P, E, E]","[P, P, G, G, E]"
307,E0,19/02/94,Everton,Arsenal,1.0,1.0,D,"[P, G, P, G, E]","[G, E, E, E, E]","[P, P, G, G, E]","[P, G, G, E, E]"
313,E0,26/02/94,Arsenal,Blackburn,1.0,0.0,H,"[E, E, E, E, E]","[G, G, G, G, E]","[E, G, G, E, E]","[E, G, G, G, E]"
325,E0,05/03/94,Ipswich,Arsenal,1.0,5.0,A,"[E, P, P, E, G]","[E, E, E, E, G]","[G, E, P, E, G]","[G, G, E, E, E]"
350,E0,19/03/94,Southampton,Arsenal,0.0,4.0,A,"[P, G, G, E, E]","[E, E, E, G, G]","[P, G, G, G, E]","[G, E, E, E, G]"
356,E0,22/03/94,Arsenal,Man United,2.0,2.0,D,"[E, E, G, G, G]","[G, E, P, G, E]","[G, G, E, E, G]","[E, G, G, E, E]"
358,E0,26/03/94,Arsenal,Liverpool,1.0,0.0,H,"[E, G, G, G, E]","[P, G, P, G, G]","[G, E, E, G, E]","[G, E, P, P, P]"
376,E0,02/04/94,Arsenal,Swindon,1.0,1.0,D,"[G, G, G, E, G]","[P, E, P, E, P]","[E, E, G, E, G]","[P, P, P, P, P]"
392,E0,04/04/94,Sheffield United,Arsenal,1.0,1.0,D,"[E, E, E, G, G]","[G, G, E, G, E]","[E, E, E, E, G]","[E, E, E, G, G]"
405,E0,16/04/94,Arsenal,Chelsea,1.0,0.0,H,"[G, E, G, E, E]","[G, P, G, E, E]","[E, G, E, G, E]","[G, P, P, E, E]"
416,E0,19/04/94,Arsenal,Wimbledon,1.0,1.0,D,"[E, G, E, E, G]","[G, G, G, E, G]","[G, E, G, E, G]","[P, G, P, P, G]"
417,E0,23/04/94,Aston Villa,Arsenal,1.0,2.0,A,"[E, P, E, P, G]","[G, E, E, G, E]","[E, P, P, E, E]","[E, E, G, G, E]"
432,E0,27/04/94,QPR,Arsenal,1.0,1.0,D,"[P, P, E, G, E]","[E, E, G, E, G]","[E, G, P, E, G]","[E, G, G, E, G]"
434,E0,30/04/94,Arsenal,West Ham,0.0,2.0,A,"[E, G, E, G, E]","[G, P, G, P, P]","[E, G, E, G, E]","[E, P, P, G, G]"
455,E0,07/05/94,Newcastle,Arsenal,2.0,0.0,H,"[P, G, G, G, P]","[G, E, G, E, P]","[G, G, E, G, G]","[G, G, E, G, E]"