In [26]:
import numpy as np
import pandas as pd

from collections import deque

In [27]:
df = pd.read_csv("../data/raw/1993-94.csv")
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,E0,14/08/93,Arsenal,Coventry,0.0,3.0,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/93,Aston Villa,QPR,4.0,1.0,H,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/93,Chelsea,Blackburn,1.0,2.0,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/93,Liverpool,Sheffield Weds,2.0,0.0,H,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/93,Man City,Leeds,1.0,1.0,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.shape

(552, 28)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Div          462 non-null    str
 1   Date         462 non-null    str
 2   HomeTeam     462 non-null    str
 3   AwayTeam     462 non-null    str
 4   FTHG         462 non-null    float64
 5   FTAG         462 non-null    float64
 6   FTR          462 non-null    str
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  0 non-null      float64
 15  Unnamed: 15  0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  Unnamed: 23  0 non-null      float64
 24  Unnamed: 24  0 non-null      float64
 25  Unnamed: 25  0 non-null      float64
 26  Unnamed: 26  0 non-null      float64
 27  Unnamed: 27  0 non-null      float64
dtypes: float64(23), str(5)
memory usage: 120.9 KB

In [30]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       462 non-null    str
 1   Date      462 non-null    str
 2   HomeTeam  462 non-null    str
 3   AwayTeam  462 non-null    str
 4   FTHG      462 non-null    float64
 5   FTAG      462 non-null    float64
 6   FTR       462 non-null    str
dtypes: float64(2), str(5)
memory usage: 30.3 KB

In [32]:
# Diccionario para guardar historial de cada equipo
historial = {}

# Listas para almacenar resultados
rachas_home = []
rachas_away = []

for idx, row in df.iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    # Racha de los últimos 5 (excluyendo partido actual) - como LISTA
    racha_home = historial.get(home, [])[-5:] if home in historial else []
    racha_away = historial.get(away, [])[-5:] if away in historial else []
    
    rachas_home.append(racha_home if racha_home else [])  # Lista vacía si no hay historial
    rachas_away.append(racha_away if racha_away else [])
    
    # Actualizar historial con resultado de ESTE partido
    if row['FTR'] == 'H':
        historial.setdefault(home, []).append('G')
        historial.setdefault(away, []).append('P')
    elif row['FTR'] == 'A':
        historial.setdefault(home, []).append('P')
        historial.setdefault(away, []).append('G')
    else:  # 'D'
        historial.setdefault(home, []).append('E')
        historial.setdefault(away, []).append('E')

# Añadir al DataFrame
df['racha_home'] = rachas_home
df['racha_away'] = rachas_away

In [33]:
df[(df["HomeTeam"] == "Arsenal") | (df["AwayTeam"] == "Arsenal")]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,racha_home,racha_away
0,E0,14/08/93,Arsenal,Coventry,0.0,3.0,A,[],[]
11,E0,16/08/93,Tottenham,Arsenal,0.0,1.0,A,[G],[P]
29,E0,21/08/93,Sheffield Weds,Arsenal,0.0,1.0,A,"[P, E]","[P, G]"
34,E0,24/08/93,Arsenal,Leeds,2.0,1.0,H,"[P, G, G]","[E, G, P]"
45,E0,28/08/93,Arsenal,Everton,2.0,0.0,H,"[P, G, G, G]","[G, G, G, P]"
59,E0,01/09/93,Blackburn,Arsenal,1.0,1.0,D,"[G, P, G, G, E]","[P, G, G, G, G]"
66,E0,11/09/93,Arsenal,Ipswich,4.0,0.0,H,"[G, G, G, G, E]","[G, G, P, E, E]"
86,E0,19/09/93,Man United,Arsenal,1.0,0.0,H,"[E, G, G, G, P]","[G, G, G, E, G]"
88,E0,25/09/93,Arsenal,Southampton,1.0,0.0,H,"[G, G, E, G, P]","[G, P, P, P, P]"
101,E0,02/10/93,Liverpool,Arsenal,0.0,0.0,D,"[G, P, P, P, P]","[G, E, G, P, G]"
110,E0,16/10/93,Arsenal,Man City,0.0,0.0,D,"[E, G, P, G, E]","[G, G, P, G, E]"
126,E0,23/10/93,Oldham,Arsenal,0.0,0.0,D,"[P, P, E, E, P]","[G, P, G, E, E]"
132,E0,30/10/93,Arsenal,Norwich,0.0,0.0,D,"[P, G, E, E, E]","[E, G, G, G, E]"
143,E0,06/11/93,Arsenal,Aston Villa,1.0,2.0,A,"[G, E, E, E, E]","[E, P, E, G, G]"
156,E0,20/11/93,Chelsea,Arsenal,0.0,2.0,A,"[P, P, P, P, P]","[E, E, E, E, P]"
174,E0,24/11/93,West Ham,Arsenal,0.0,0.0,D,"[E, E, G, P, G]","[E, E, E, P, G]"
175,E0,27/11/93,Arsenal,Newcastle,2.0,1.0,H,"[E, E, P, G, E]","[P, G, G, G, G]"
186,E0,04/12/93,Coventry,Arsenal,1.0,0.0,H,"[E, G, E, P, P]","[E, P, G, E, G]"
197,E0,06/12/93,Arsenal,Tottenham,1.0,1.0,D,"[P, G, E, G, P]","[P, E, E, E, P]"
214,E0,12/12/93,Arsenal,Sheffield Weds,1.0,0.0,H,"[G, E, G, P, E]","[E, G, G, G, E]"
220,E0,18/12/93,Leeds,Arsenal,2.0,1.0,H,"[E, G, G, G, P]","[E, G, P, E, G]"
234,E0,27/12/93,Swindon,Arsenal,0.0,4.0,A,"[P, E, P, E, G]","[G, P, E, G, P]"
240,E0,29/12/93,Arsenal,Sheffield United,3.0,0.0,H,"[P, E, G, P, G]","[E, P, E, P, E]"
256,E0,01/01/94,Wimbledon,Arsenal,0.0,3.0,A,"[P, G, G, P, E]","[E, G, P, G, G]"
257,E0,03/01/94,Arsenal,QPR,0.0,0.0,D,"[G, P, G, G, G]","[P, G, G, E, P]"
267,E0,15/01/94,Man City,Arsenal,0.0,0.0,D,"[G, P, P, E, P]","[P, G, G, G, E]"
275,E0,22/01/94,Arsenal,Oldham,1.0,1.0,D,"[G, G, G, E, E]","[E, P, P, P, P]"
303,E0,13/02/94,Norwich,Arsenal,1.0,1.0,D,"[G, P, E, E, E]","[G, G, E, E, E]"
307,E0,19/02/94,Everton,Arsenal,1.0,1.0,D,"[P, G, P, G, E]","[G, E, E, E, E]"
313,E0,26/02/94,Arsenal,Blackburn,1.0,0.0,H,"[E, E, E, E, E]","[G, G, G, G, E]"
325,E0,05/03/94,Ipswich,Arsenal,1.0,5.0,A,"[E, P, P, E, G]","[E, E, E, E, G]"
350,E0,19/03/94,Southampton,Arsenal,0.0,4.0,A,"[P, G, G, E, E]","[E, E, E, G, G]"
356,E0,22/03/94,Arsenal,Man United,2.0,2.0,D,"[E, E, G, G, G]","[G, E, P, G, E]"
358,E0,26/03/94,Arsenal,Liverpool,1.0,0.0,H,"[E, G, G, G, E]","[P, G, P, G, G]"
376,E0,02/04/94,Arsenal,Swindon,1.0,1.0,D,"[G, G, G, E, G]","[P, E, P, E, P]"
392,E0,04/04/94,Sheffield United,Arsenal,1.0,1.0,D,"[E, E, E, G, G]","[G, G, E, G, E]"
405,E0,16/04/94,Arsenal,Chelsea,1.0,0.0,H,"[G, E, G, E, E]","[G, P, G, E, E]"
416,E0,19/04/94,Arsenal,Wimbledon,1.0,1.0,D,"[E, G, E, E, G]","[G, G, G, E, G]"
417,E0,23/04/94,Aston Villa,Arsenal,1.0,2.0,A,"[E, P, E, P, G]","[G, E, E, G, E]"
432,E0,27/04/94,QPR,Arsenal,1.0,1.0,D,"[P, P, E, G, E]","[E, E, G, E, G]"
434,E0,30/04/94,Arsenal,West Ham,0.0,2.0,A,"[E, G, E, G, E]","[G, P, G, P, P]"
455,E0,07/05/94,Newcastle,Arsenal,2.0,0.0,H,"[P, G, G, G, P]","[G, E, G, E, P]"

In [44]:
df.tail(60)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,racha_home,racha_away
492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"
551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[E, E, E, E, E]","[E, E, E, E, E]"